### ISSUE TITLE
[fix] 글 작성 페이지 수정

### ISSUE THREAD

**Issue by iamseoyoung** [Neulbom1234/Neulbom#12]
## Issue 📌
글 작성 페이지 수정
## Todo ✔️
- [x] 파일 찾기 버튼 cursor : pointer; 추가
- [x] 카테고리 option 추가
- [x] 미용실 찾기 페이지 추가
