### ISSUE TITLE
[fix] 미흡한 기능들 수정

### ISSUE THREAD

**Issue by coral0723** [Neulbom1234/Neulbom#58]
## Issue 📌
백엔드 연결 전 미흡한 부분들 수정
## Todo ✔️
- [x] 게시글 상세 페이지에 카테고리 추가
- [x] 검색 페이지 카테고리에 state 추가
- [x] 유저 페이지 css 수정
- [x] 검색어 입력하면 검색창에 검색어가 남아있게 수정
